#!/usr/bin/env bash

source utils.sh

chmod +x /home/${CONTAINER_USER:?}/lib/invPtrLoc.config
chmod +x /home/${CONTAINER_USER:?}/lib/fmw_12.1.3.0.0_wls.jar
tar -xvf jdk-8u291-linux-x64.tar.gz --directory /home/${CONTAINER_USER:?}/lib/ || exit_on_error
chown ${CONTAINER_USER:?}:${CONTAINER_USER:?} /home/${CONTAINER_USER:?}/lib/*

./createCentralInventory.sh /home/${CONTAINER_USER:?}/lib/Inventroy ${CONTAINER_USER:?}

su -c 'export PATH=/home/'${CONTAINER_USER:?}'/lib/jdk1.8.0_291/bin:${PATH} && export JAVA_HOME=/home/'${CONTAINER_USER:?}'/lib/jdk1.8.0_291 && /home/'${CONTAINER_USER:?}'/lib/script-run-inst-weblogic' ${CONTAINER_USER:?}
